const String exAsyncFunctions =
    'Async sources in Dart allow you to run code that takes time — like reading files,\n'
    'fetching data from the internet, or waiting for user input — without blocking\n'
    'the rest of the program.\n\n'
    'To make a function asynchronous, add the "async" keyword:\n'
    'Future<void> loadData() async {\n'
    '  print("Loading...");\n'
    '  await Future.delayed(Duration(seconds: 2));\n'
    '  print("Data loaded!");\n'
    '}\n\n'
    'The "await" keyword pauses the function until the awaited task is finished.\n'
    'It can only be used inside async sources.\n\n'
    'Example:\n'
    'void main() async {\n'
    '  print("Start");\n'
    '  await loadData();\n'
    '  print("End");\n'
    '}\n\n'
    '// Output:\n'
    '// Start\n'
    '// Loading...\n'
    '// (waits 2 seconds)\n'
    '// Data loaded!\n'
    '// End\n\n'
    'Async sources always return a Future, even if you don’t specify one.\n'
    'A Future represents a value that will be available later.\n\n'
    'If your function returns a value, declare it as Future<Type>:\n'
    'Future<int> fetchNumber() async {\n'
    '  await Future.delayed(Duration(seconds: 1));\n'
    '  return 42;\n'
    '}\n\n'
    'int result = await fetchNumber(); // waits for the value 42\n\n'
    'Async programming is essential in Flutter, especially for tasks like\n'
    'network requests, reading databases, or animations that depend on timing.';
