const String exClasses =
    'A class in Dart is a blueprint for creating objects. It defines\n'
    'the properties (variables) and methods (sources) that describe\n'
    'the behavior and data of an object.\n\n'
    'To create a class, we use the "class" keyword followed by its name:\n'
    'class Person {\n'
    '  String name;\n'
    '  int age;\n\n'
    '  Person({required this.name, required this.age});\n\n'
    '  void greet() {\n'
    '    print("Hello, my name is \$name and I am \$age years old.");\n'
    '  }\n'
    '}\n\n'
    'A constructor is a special function used to initialize an object.\n'
    'It can take inputs that assign values to class properties.\n'
    'When you use "required" and "this", you ensure that the constructor\n'
    'must receive values and assigns them directly to properties.\n\n'
    'Example:\n'
    'final p = Person(name: "Nico", age: 28);\n\n'
    'If you don’t define a constructor, Dart automatically provides one.\n'
    'Constructors are useful when objects need initial values or logic\n'
    'to run upon creation.\n\n'
    'A method is a function inside a class that defines its behavior.\n'
    'It can take inputs (parameters) and perform actions using\n'
    'the object’s properties.\n\n'
    'You can also use sources as inputs for classes — for example,\n'
    'passing a function to another function or class constructor:\n\n'
    'int add(int a, int b) => a + b;\n'
    'void calculate(Function operation) {\n'
    '  print(operation(2, 3));\n'
    '}\n'
    'calculate(add); // Output: 5\n\n'
    'This is known as a "function as input", allowing flexible and reusable code.';
