const String columnTextual =
    'Column is a layout widget in Flutter that arranges its child widgets\n'
    'vertically, from top to bottom. It is useful when you want to stack\n'
    'multiple widgets in a vertical sequence.\n\n'
    'Columns can be customized with properties like mainAxisAlignment\n'
    'and crossAxisAlignment to control how children are positioned\n'
    'vertically and horizontally within the available space.\n\n'
    'Typically, Column is used inside containers, scaffolds, or other\n'
    'layout widgets to create vertical layouts that adjust dynamically\n'
    'based on screen size and content.';
const String rowTextual =
    'Row is a layout widget in Flutter that arranges its child widgets\n'
    'horizontally, from left to right. It is useful when you want to\n'
    'display multiple widgets side by side.\n\n'
    'Rows can be customized with properties like mainAxisAlignment\n'
    'and crossAxisAlignment to control how children are aligned\n'
    'horizontally and vertically within the available space.\n\n'
    'Typically, Row is used inside containers, columns, or other\n'
    'layout widgets to create horizontal layouts that adapt dynamically\n'
    'to different screen sizes and content.';
const String columnExample =
    'class MyColumnWidget extends StatelessWidget {\n'
    '  @override\n'
    '  Widget build(BuildContext context) {\n'
    '    return Column(\n'
    '      mainAxisAlignment: MainAxisAlignment.center,\n'
    '      crossAxisAlignment: CrossAxisAlignment.start,\n'
    '      children: [\n'
    '        Text("First item"),\n'
    '        Text("Second item"),\n'
    '        Text("Third item"),\n'
    '      ],\n'
    '    );\n'
    '  }\n'
    '}';
const String rowExample =
    'class MyRowWidget extends StatelessWidget {\n'
    '  @override\n'
    '  Widget build(BuildContext context) {\n'
    '    return Row(\n'
    '      mainAxisAlignment: MainAxisAlignment.spaceAround,\n'
    '      crossAxisAlignment: CrossAxisAlignment.center,\n'
    '      children: [\n'
    '        Icon(Icons.star),\n'
    '        Icon(Icons.favorite),\n'
    '        Icon(Icons.share),\n'
    '      ],\n'
    '    );\n'
    '  }\n'
    '}';
