const String exComposition =
    "In Flutter, when working with an ExpansionTile, you can break it down into smaller, reusable widgets by separating the parent tile from its children.\n\n"
    "1. Create a data model for the tile:\n"
    "   - This holds the title and the list of child items.\n\n"
    "   class TileData {\n"
    "     final String title;\n"
    "     final List<String> children;\n"
    "     TileData({required this.title, required this.children});\n"
    "   }\n\n"
    "2. Create a widget for the child items:\n"
    "   - Each child can be represented as a separate ListTile or custom widget.\n\n"
    "   class ChildItem extends StatelessWidget {\n"
    "     final String text;\n"
    "     const ChildItem({required this.text});\n\n"
    "     @override\n"
    "     Widget build(BuildContext context) {\n"
    "       return ListTile(title: Text(text));\n"
    "     }\n"
    "   }\n\n"
    "3. Create a widget for the parent ExpansionTile:\n"
    "   - Pass the TileData to it and map the children data to ChildItem widgets.\n\n"
    "   class MyExpansionTile extends StatelessWidget {\n"
    "     final TileData data;\n"
    "     const MyExpansionTile({required this.data});\n\n"
    "     @override\n"
    "     Widget build(BuildContext context) {\n"
    "       return ExpansionTile(\n"
    "         title: Text(data.title),\n"
    "         children: data.children.map((child) => ChildItem(text: child)).toList(),\n"
    "       );\n"
    "     }\n"
    "   }\n\n"
    "4. Compose the UI:\n"
    "   - Use multiple MyExpansionTile instances with different TileData.\n\n"
    "   final tiles = [\n"
    "     TileData(title: 'Fruits', children: ['Apple', 'Banana', 'Orange']),\n"
    "     TileData(title: 'Vegetables', children: ['Carrot', 'Lettuce', 'Tomato']),\n"
    "   ];\n\n"
    "   Column(\n"
    "     children: tiles.map((tile) => MyExpansionTile(data: tile)).toList(),\n"
    "   );\n\n"
    "Note on toList():\n"
    "- The map() function returns an Iterable, not a List.\n"
    "- toList() converts the Iterable into a List, which is required by the 'children' property of ExpansionTile.\n\n"
    "By separating parent and children into their own widgets and using a data model, you gain:\n"
    "- Reusability: reuse MyExpansionTile with any data.\n"
    "- Maintainability: update child widget in one place.\n"
    "- Flexibility: each tile or child can have custom behavior independently.\n"
    "- Clean code: the UI is modular and easy to read.\n";
