const String exExternalization =
    "In Flutter (and Dart), externalizing a function means moving it from your main file to a separate file.\n"
    "This helps keep your code clean, modular, and easier to maintain.\n\n"
    "1. Create a new Dart file for your function, e.g., 'utils.dart'.\n\n"
    "   // utils.dart\n"
    "   String greetUser(String name) {\n"
    "     return 'Hello, \$name!';\n"
    "   }\n\n"
    "2. Export the function so it can be used in other files.\n"
    "   - In Dart, just defining it as above is enough; functions are public by default if not private (i.e., no leading underscore).\n\n"
    "3. Import the external file in your main file.\n\n"
    "   // main.dart\n"
    "   import 'utils.dart';\n\n"
    "4. Call the external function in your main file.\n\n"
    "   void main() {\n"
    "     String message = greetUser('Nico');\n"
    "     print(message); // Output: Hello, Nico!\n"
    "   }\n\n"
    "Benefits of externalizing functions:\n"
    "- Code cleanliness: main file stays focused on UI or main logic.\n"
    "- Reusability: the same function can be used across multiple files.\n"
    "- Maintainability: updating the function in one place updates all usages.\n"
    "- Easier testing: you can test the function independently from the UI.\n\n"
    "This practice is especially useful when you have helper functions, validators, API calls, or complex logic that shouldn't clutter your widgets.";
