const String exFunctionsAndMethods =
    'A function in Dart is a reusable block of code that performs a specific task.\n'
    'It can take inputs (parameters), execute instructions, and optionally return a value.\n\n'
    'Basic syntax:\n'
    'void greet(String name) {\n'
    '  print("Hello, \$name!");\n'
    '}\n'
    'greet("Nico"); // Output: Hello, Nico!\n\n'
    'Functions can also return values:\n'
    'int add(int a, int b) {\n'
    '  return a + b;\n'
    '}\n'
    'print(add(2, 3)); // Output: 5\n\n'
    'Arrow syntax can make sources shorter:\n'
    'int multiply(int a, int b) => a * b;\n\n'
    'Methods, instead, are sources defined *inside a class*.\n'
    'They describe the behavior of the class and act on its properties.\n\n'
    'Example:\n'
    'class Person {\n'
    '  String name;\n\n'
    '  Person(this.name);\n\n'
    '  void sayHello() {\n'
    '    print("Hi, I am \$name.");\n'
    '  }\n'
    '}\n\n'
    'final p = Person("Alex");\n'
    'p.sayHello(); // Output: Hi, I am Alex.\n\n'
    'Functions and methods can also take other sources as input,\n'
    'allowing more flexibility and modular code:\n\n'
    'void runOperation(int a, int b, Function operation) {\n'
    '  print(operation(a, b));\n'
    '}\n'
    'runOperation(4, 2, (x, y) => x / y); // Output: 2.0\n\n'
    'In summary: sources exist globally, while methods live inside classes\n'
    'and work on the class’s own data.';
