const String exIfElse =
    'The if / else if / else structure in Dart is used to control the flow of code\n'
    'based on logical conditions. It checks whether a statement is true or false\n'
    'and executes different blocks of code accordingly.\n\n'
    'Basic syntax:\n'
    'if (condition) {\n'
    '  // code runs if condition is true\n'
    '} else if (anotherCondition) {\n'
    '  // runs if the first condition is false but this one is true\n'
    '} else {\n'
    '  // runs if none of the above conditions are true\n'
    '}\n\n'
    'Example:\n'
    'int score = 85;\n'
    'if (score >= 90) {\n'
    '  print("Grade: A");\n'
    '} else if (score >= 80) {\n'
    '  print("Grade: B");\n'
    '} else {\n'
    '  print("Grade: C");\n'
    '}\n'
    '// Output: Grade: B\n\n'
    'You can combine multiple logical expressions using operators:\n'
    '&& (and), || (or), and ! (not)\n\n'
    'Example:\n'
    'if (age >= 18 && hasID) {\n'
    '  print("Access granted");\n'
    '} else {\n'
    '  print("Access denied");\n'
    '}\n\n'
    'It’s important to note that Dart evaluates conditions from top to bottom —\n'
    'the first true condition will execute, and the rest are skipped.\n\n'
    'You can also use single-line shorthand:\n'
    'if (isActive) print("Active"); else print("Inactive");\n\n'
    'In Flutter, if / else statements are often used to render different widgets\n'
    'based on state, for example:\n'
    'child: isLoading ? CircularProgressIndicator() : Text("Loaded!");';
