const String exLists =
    'A List in Dart is an ordered collection of items, similar to an array\n'
    'in other programming languages. Each item in a list has an index,\n'
    'starting from 0 for the first element.\n\n'
    'To create a list, you can use square brackets [] or the List() constructor:\n'
    'List<String> names = ["Nico", "Alex", "Sam"];\n'
    'var numbers = [1, 2, 3, 4, 5];\n\n'
    'You can access elements using their index:\n'
    'print(names[0]); // Output: Nico\n\n'
    'Lists are dynamic — you can add, remove, or modify items:\n'
    'names.add("Luca");              // Adds an item at the end\n'
    'names.remove("Alex");           // Removes an item by value\n'
    'names.removeAt(1);              // Removes an item by index\n'
    'names.insert(0, "NewName");     // Inserts an item at index 0\n'
    'names[2] = "UpdatedName";       // Updates a specific element\n\n'
    'You can also use useful properties and methods:\n'
    'names.length;   // Returns the number of items\n'
    'names.isEmpty;  // Checks if the list is empty\n'
    'names.contains("Nico"); // Checks if an element exists\n\n'
    'You can loop through a list using for or forEach:\n'
    'for (var n in names) {\n'
    '  print(n);\n'
    '}\n\n'
    'Lists can store any type, even objects or other lists:\n'
    'List<dynamic> mixed = ["Text", 42, true, [1, 2, 3]];\n\n'
    'You can also use List.generate() to create lists dynamically:\n'
    'var squares = List.generate(5, (index) => index * index);\n'
    'print(squares); // Output: [0, 1, 4, 9, 16]\n\n'
    'In Flutter, lists are fundamental to display collections of widgets,\n'
    'for example using ListView.builder(), which efficiently builds UI\n'
    'elements based on list data.\n\n'
    'In summary, Lists in Dart are powerful, flexible, and essential for\n'
    'storing and manipulating ordered data.';
