const String exMap =
    'A Map in Dart is a collection of key-value pairs, where each key\n'
    'is unique and is used to access its corresponding value.\n\n'
    'Maps are useful for storing and retrieving data efficiently\n'
    'when you need to associate specific identifiers (keys)\n'
    'with particular values.\n\n'
    'You can create a Map using curly braces { } or the Map() constructor.\n'
    'For example:\n'
    'var myMap = {\'name\': \'Nico\', \'age\': 28, \'city\': \'Rome\'};\n\n'
    'Values can be accessed using their keys, like:\n'
    'print(myMap[\'name\']); // Output: Nico\n\n'
    'Maps can also be modified dynamically by adding, updating,\n'
    'or removing key-value pairs.\n\n'
    'To add or update an entry:\n'
    'myMap[\'job\'] = \'Developer\'; // Adds a new key-value pair\n'
    'myMap[\'age\'] = 29;           // Updates an existing value\n\n'
    'To remove an entry:\n'
    'myMap.remove(\'city\');        // Removes the key \'city\' and its value\n\n'
    'To clear all entries:\n'
    'myMap.clear();                 // Removes all key-value pairs\n\n'
    'You can also check if a key exists:\n'
    'print(myMap.containsKey(\'name\')); // true or false\n\n'
    'Maps are a fundamental data structure in Dart for organizing\n'
    'and managing related information in a flexible way.';
