const String exNavigatorNamedRoutes =
    'Named routes in Flutter provide a clean and organized way\n'
    'to navigate between screens using string identifiers instead\n'
    'of directly creating MaterialPageRoute objects.\n\n'
    'First, you define your routes inside the MaterialApp widget,\n'
    'usually in the main.dart file:\n\n'
    'MaterialApp(\n'
    '  initialRoute: \'/\',\n'
    '  routes: {\n'
    '    \'/\': (context) => HomePage(),\n'
    '    \'/second\': (context) => SecondPage(),\n'
    '    \'/profile\': (context) => ProfilePage(),\n'
    '  },\n'
    ');\n\n'
    'Each key (like "/second") represents a named route,\n'
    'and its value is a function that builds the corresponding widget.\n\n'
    'To navigate to a named route, use:\n'
    'Navigator.pushNamed(context, \'/second\');\n\n'
    'To go back to the previous route:\n'
    'Navigator.pop(context);\n\n'
    'You can also pass arguments when navigating:\n'
    'Navigator.pushNamed(\n'
    '  context,\n'
    '  \'/profile\',\n'
    '  arguments: {\'username\': \'Nico\', \'age\': 28},\n'
    ');\n\n'
    'Inside the destination widget, retrieve the arguments like this:\n'
    'final args = ModalRoute.of(context)!.settings.arguments as Map;\n'
    'print(args[\'username\']); // Output: Nico\n\n'
    'Named routes are especially useful for large apps,\n'
    'as they keep navigation consistent and easy to maintain.';
