const String exNullOperator =
    'The null operator in Dart helps you handle variables that might have no value (null)\n'
    'without causing runtime errors. It provides a safe way to check, assign, or return values\n'
    'when something is null.\n\n'
    'Dart offers several null-related operators:\n\n'
    '1️⃣ Null-aware access operator (?.)\n'
    'It allows you to safely access a property or method only if the object is not null.\n'
    'Example:\n'
    'String? name;\n'
    'print(name?.length); // Output: null (instead of an error)\n\n'
    '2️⃣ Null-coalescing operator (??)\n'
    'It provides a default value if the expression on the left is null.\n'
    'Example:\n'
    'String? username;\n'
    'print(username ?? "Guest"); // Output: Guest\n\n'
    '3️⃣ Null-assignment operator (??=)\n'
    'It assigns a value only if the variable is currently null.\n'
    'Example:\n'
    'int? age;\n'
    'age ??= 18;\n'
    'print(age); // Output: 18\n\n'
    '4️⃣ Null assertion operator (!)\n'
    'It tells Dart that you are *sure* the value is not null, and forces access.\n'
    'If the value is actually null, it throws an error at runtime.\n'
    'Example:\n'
    'String? city;\n'
    'print(city!); // ⚠️ Throws an error because city is null\n\n'
    'These operators are extremely useful when working with nullable variables,\n'
    'optional parameters, or asynchronous data that might not yet exist.\n\n'
    'In Flutter, you’ll often see them in widget trees:\n'
    'Text(user?.name ?? "Unknown user")\n\n'
    'In summary:\n'
    ' - ?. → safely access if not null\n'
    ' - ?? → provide a fallback value\n'
    ' - ??= → assign only if null\n'
    ' - ! → assert it’s not null\n\n'
    'Used wisely, null operators make your code cleaner, safer, and more concise.';
