const String exTryCatch =
    'The try / catch structure in Dart is used to handle errors and exceptions gracefully,\n'
    'preventing your program from crashing when something goes wrong.\n\n'
    'Basic syntax:\n'
    'try {\n'
    '  // code that might throw an error\n'
    '} catch (e) {\n'
    '  // code that runs if an error occurs\n'
    '}\n\n'
    'Example:\n'
    'try {\n'
    '  int result = 10 ~/ 0; // Integer division by zero\n'
    '  print(result);\n'
    '} catch (e) {\n'
    '  print("An error occurred: \$e");\n'
    '}\n'
    '// Output: An error occurred: IntegerDivisionByZeroException\n\n'
    'You can also add a "finally" block that always runs — whether or not an error occurred:\n'
    'try {\n'
    '  File file = File("data.txt");\n'
    '  var content = file.readAsStringSync();\n'
    '  print(content);\n'
    '} catch (e) {\n'
    '  print("File not found: \$e");\n'
    '} finally {\n'
    '  print("Operation complete.");\n'
    '}\n\n'
    'You can catch specific error types using "on":\n'
    'try {\n'
    '  var number = int.parse("abc");\n'
    '} on FormatException catch (e) {\n'
    '  print("Invalid format: \$e");\n'
    '} catch (e) {\n'
    '  print("Unknown error: \$e");\n'
    '}\n\n'
    'The "throw" keyword is used to *manually* raise an exception.\n'
    'You can throw built-in or custom errors to stop execution intentionally:\n'
    'void checkAge(int age) {\n'
    '  if (age < 18) {\n'
    '    throw Exception("You must be at least 18 years old.");\n'
    '  } else {\n'
    '    print("Access granted.");\n'
    '  }\n'
    '}\n\n'
    'try {\n'
    '  checkAge(16);\n'
    '} catch (e) {\n'
    '  print("Error: \$e");\n'
    '}\n'
    '// Output: Error: Exception: You must be at least 18 years old.\n\n'
    'Using "throw" lets you create your own custom error flow,\n'
    'and "try / catch / finally" ensures your app handles those errors safely.\n'
    'Together, they form Dart’s complete system for *exception handling*.';
